title: Naming things is hard.
description: 
author: Marcus Lim
github: https://github.com/marcuslimdw
about: I like coding, solving problems and building things.
# disqus_shortname: stackproblems
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: ['computer-engineering', 'statistics', 'animation', 'data-science', 'machine-learning', 'monte-carlo', 'personal', 'classification', 'python', 'clt', 'game']

# collections:
#   project:
#     output: true
#     permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "#"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/marcusldw"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/11015427/gmds"
    - icon: fa-github
      link: "https://github.com/marcuslimdw"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://marcuslimdw.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
mathjax: true
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
